definitions:
  common.Response:
    properties:
      Detail:
        type: object
      Message:
        type: string
      Status:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /test:
    get:
      parameters:
      - description: test api
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/common.Response'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Response'
      summary: Get Auth
      tags:
      - Test
swagger: "2.0"
